services:
  - type: web
    name: chatflow
    env: node
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://chatflow.onrender.com
    buildFilter:
      paths:
        - src/**
        - server/**
        - package.json
        - tsconfig.json
        - vite.config.ts
